server:
  port: 8082

logging:
  level:
    org.springframework.jdbc: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '12345678'
    url: 'jdbc:mysql://localhost:3306/product_db'